---
- name: Ensure /etc/skel exists
  file:
    path: /etc/skel
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Sync physical skel from repo (directories)
  file:
    path: "/etc/skel/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - public_html
    - public_html/cgi-bin
    - public_gemini
    - public_gopher
    - bin

- name: Create .ssh with strict permissions
  file:
    path: /etc/skel/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Place README_FIRST.txt
  copy:
    src: ../../../config/skel/README_FIRST.txt
    dest: /etc/skel/README_FIRST.txt
    owner: root
    group: root
    mode: "0644"

- name: Place .plan and .project templates
  copy:
    src: "../../../config/skel/{{ item }}"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - .plan
    - .project

- name: Place default index.html
  copy:
    src: ../../../config/skel/public_html/index.html
    dest: /etc/skel/public_html/index.html
    owner: root
    group: root
    mode: "0644"

- name: Place CGI README
  copy:
    src: ../../../config/skel/public_html/README_CGI.txt
    dest: /etc/skel/public_html/README_CGI.txt
    owner: root
    group: root
    mode: "0644"

- name: Place default index.gmi for Gemini
  copy:
    src: ../../../config/skel/public_gemini/index.gmi
    dest: /etc/skel/public_gemini/index.gmi
    owner: root
    group: root
    mode: "0644"

- name: Place default gophermap
  copy:
    src: ../../../config/skel/public_gopher/gophermap
    dest: /etc/skel/public_gopher/gophermap
    owner: root
    group: root
    mode: "0644"

- name: Place .profile
  copy:
    src: ../../../config/skel/.profile
    dest: /etc/skel/.profile
    owner: root
    group: root
    mode: "0644"

- name: Place .bashrc
  copy:
    src: ../../../config/skel/.bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: "0644"

- name: Place SSH client sample config
  copy:
    src: ../../../config/skel/.ssh/config
    dest: /etc/skel/.ssh/config
    owner: root
    group: root
    mode: "0600"
