version: '3.8'

services:
  pubnix-test:
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile.test
    container_name: atl-pubnix-test
    environment:
      - PUBNIX_ENV=testing
      - PUBNIX_DEBUG=false
      - PUBNIX_LOG_LEVEL=INFO
    volumes:
      - ../../tests:/opt/pubnix/tests
      - test_results:/opt/pubnix/test-results
    networks:
      - pubnix-test-net
    command: ["python", "-m", "pytest", "tests/", "-v", "--junitxml=/opt/pubnix/test-results/junit.xml"]

  test-db:
    image: postgres:15-alpine
    container_name: atl-pubnix-test-db
    environment:
      - POSTGRES_DB=pubnix_test
      - POSTGRES_USER=pubnix_test
      - POSTGRES_PASSWORD=test_password
    networks:
      - pubnix-test-net
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  test_results:

networks:
  pubnix-test-net:
    driver: bridge